name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: make giftcardreader
        run:
          make giftcardreader
      - name: make crash1
        run:
          make crash1
      - name: make crash2
        if: ${{failure()}}
        run:
          make crash2
      - name: make hang
        if: ${{failure()}}
        run:
          make hang
      - name: make fuzz1
        if: ${{failure()}}
        run:
          make fuzz1
      - name: make fuzz2
        if: ${{failure()}}
        run:
          make fuzz1
